import { defineConfig } from 'vitest/config'

export default defineConfig({
  esbuild: {
    // Avoid packages/extension/tsconfig.json → ./.wxt (generated by `wxt prepare`).
    tsconfigRaw: {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        skipLibCheck: true,
        isolatedModules: true,
        jsx: 'react-jsx',
      },
    },
  },
  test: {
    environment: 'jsdom',
    include: ['lib/**/*.test.ts', 'entrypoints/**/*.test.{ts,tsx}'],
  },
})
