export default {
  esbuild: {
    // Avoid packages/extension/tsconfig.json → ./.wxt (generated by `wxt prepare`).
    tsconfigRaw: {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        skipLibCheck: true,
        isolatedModules: true,
      },
    },
  },
  test: {
    environment: 'node',
    include: ['lib/**/*.{test,spec}.ts'],
  },
}
